version: '3.8'

services:
  app:
    image: nullstone/node:local
    command: yarn start
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
